Revert "[lookandfeel kcm] Do not declare plugin in lookandfeeltool code version"
This reverts commit 502e8dc1080fc42bd11611704484e251c23a9307.

It causes error undefined reference to 'vtable for
KCMLookandFeelFactory' while linking, as reported by psifidotos on IRC
channel.

This reverts the D10485