Fix errors detected by clang-check
src/kcm/customslider.cpp:57:48: error: default initialization of an
      object of const type 'const CustomSlider::Interpolator'
      requires a user-provided default constructor

src/kcm/touchpadconfig.cpp:140:49: error: default initialization of
      an object of const type 'const CustomSlider::SqrtInterpolator'
      requires a user-provided default constructor