Fix includes when building the kglobalaccel dbus interface
So that KGloalAccel::MatchType can be found:
In file included from /builds/plasma/plasma-desktop/kcms/keys/kcm_keys.cpp:23:
/builds/plasma/plasma-desktop/_build/kcms/keys/kglobalaccel_interface.h:129:105: error: ‘KGlobalAccel’ has not been declared
  129 |     inline QDBusPendingReply<QList<KGlobalShortcutInfo> > globalShortcutsByKey(const QKeySequence &key, KGlobalAccel::MatchType matchType)

And kglobalaccel.h already includes kglobalshortcutinfo.h