Fix building on Linux with clang/libc++
When using libc++, cmath isn't being pulled in,
resulting in

error: no member named 'sqrt' in namespace 'std'

Adding explicit include fixes it

(cherry picked from commit 3a3bbc39d5cba8d77c89f6652c5b9c24c9980497)