AppletError: Use compact error message from libplasma as the header
Approved by the Ukrainian and Dutch translation teams.

(cherry picked from commit 78ce400ee9e37f52b5858949307ba10d1e3d9b7e)