Use pkg_get_variable() to get XKBDIR
Also emit an FATAL_ERROR if xkeyboard-config is missing since right now
that results in a rather confusing build failure:
```
/Users/alex/cheri/kde-frameworks/plasma-desktop/kcms/keyboard/tastenbrett/main.cpp:42:46: error: use of undeclared identifier 'XKBDIR'
    return QStringLiteral("%1/rules/%2").arg(XKBDIR, rulesName);
                                             ^
/Users/alex/cheri/kde-frameworks/plasma-desktop/kcms/keyboard/tastenbrett/main.cpp:42:12: error: variable 'holder' cannot be implicitly captured in a lambda with no capture-default specified
    return QStringLiteral("%1/rules/%2").arg(XKBDIR, rulesName);
```